theme: jekyll-theme-minimal
title: Neural Nets Project Proposal: "Tattoo Designer"
description: This project involved a neural net that, given specifications from a user, will generate a tattoo for them.
